<h1 align="center"> R tutorial (Fundamentals) </h1>

## variable Assignment

In [29]:
x <- 5
y <- "akram"
z <- TRUE

## Printing values

In [30]:
print(x)
print(y)
print(z)

[1] 5
[1] "akram"
[1] TRUE


## Conditional Statements

In [33]:
if (x != 5) {
  print("True")
} else if (y == "akram") {
  print(y)
} else {
  print("False")
}

[1] "akram"


## Loops
### For

In [43]:
for (i in 0:3) {
  print(i)
}

[1] 0
[1] 1
[1] 2
[1] 3


### While

In [44]:
i <- 0
while (i <= 3) {
  print(i)
  i <- i + 1
}

[1] 0
[1] 1
[1] 2
[1] 3


### Functions

In [46]:
func <- function(x, y) {
  return(x + y)
}

print(func(2, 3))

[1] 5


## Maths in R

In [57]:
# square
x <- 9
x^2

# square root
sqrt(x)

# log
log(x)

# exponent
exp(x)

# ln
log2(x)

# absolute value
abs(-x)

[1] 81

[1] 3

[1] 2.197225

[1] 8103.084

[1] 3.169925

[1] 9

## Vectors and matrices
### vectors

In [85]:
v <- c(1, 3, 7, 9)
v

gender <- c("male", "female")
gender


[1] 1 3 7 9

[1] "male"   "female"

In [81]:
# sequence of number
1:5
seq(from = 1, to = 5, by = 1)
seq(from = 1, to = 5, by = 0.5)

[1] 1 2 3 4 5

[1] 1 2 3 4 5

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

In [84]:
# repeat
rep(1, times = 10)
rep(1:3, times = 3)

[1] 1 1 1 1 1 1 1 1 1 1

[1] 1 2 3 1 2 3 1 2 3

In [87]:
# operations on vectors

x <- 1:5
x
x + 5
x[1]
x[-1]
x[1:3]
x[x < 4]

[1] 1 2 3 4 5

[1]  6  7  8  9 10

[1] 1

[1] 2 3 4 5

[1] 1 2 3

[1] 1 2 3

### matrices

In [95]:
mat <- matrix(1:9, nrow = 3, byrow = TRUE)
mat
matrix(1:9, nrow = 3, byrow = FALSE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [90]:
mat[1, 2]
mat[c(1, 3), 2]

[1] 2

[1] 2 8

In [93]:
mat[1, ]
mat[, 1]


[1] 1 2 3

[1] 1 4 7

In [96]:
mat * 10

[,1] [,2] [,3]
[1,] 10   20   30  
[2,] 40   50   60  
[3,] 70   80   90